l_polish:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Škálování nad $VALUE|%0$ způsobí, že části rozhraní budou mimo obrazovku#!"
 RECOMMENDED_GUI_SCALE: "Škálování nad $VALUE|%0$ způsobí, že části rozhraní budou mimo obrazovku"
