l_polish:
 SETTING_VALUE_PERCENTAGE_WARNING:0 "$VALUE|%0X$"
 SETTING_VALUE_WARNING:0 "$VALUE|0X$"
 RECOMMENDED_GUI_SCALE:1 "Měřítko nad $VALUE|%0$ způsobí, že se rozhraní objeví mimo obrazovku"
 RECOMMENDED_GUI_SCALE_TOO_HIGH:1 "#X Měřítko nad $VALUE|%0$ způsobí, že se rozhraní objeví mimo obrazovku#!"
