l_polish:
 CAMERA_FPS:0 "První osoba"
 CAMERA_TABLETOP:0 "Stůl"
 CAMERA_WASD:0 "Styl WASD"
 GAMEPAD:0 "Gamepad"
 MOUSE_AND_KEYBOARD:0 "Myš a klávesnice"
 NO_AUTOSAVE:0 "Žádné automatické ukládání"
 OPTION_ANTI_ALIASING_DISABLED:0 "Zakázáno"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CUSTOM:0 "Vlastní"
 OPTION_DEFAULT:1 "Výchozí"
 OPTION_DISABLED:1 "Zakázáno"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Zobrazí hru pomocí celé obrazovky. Nastavení rozlišení změní, jak ostrý bude obraz."
 OPTION_FULLSCREEN:0 "Celá obrazovka"
 OPTION_HIGH:0 "Vysoké"
 OPTION_LOW:0 "Nízké"
 OPTION_MEDIUM:0 "Střední"
 OPTION_OFF:0 "Vypnuto"
 OPTION_ULTRA:1 "Ultra"
 OPTION_UPSCALE_DLSS:0 "NVIDIA DLSS"
 OPTION_UPSCALE_FSR2:0 "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_QUALITY_BALANCED:0 "Vyvážené"
 OPTION_UPSCALE_QUALITY_PERFORMANCE:0 "Výkon"
 OPTION_UPSCALE_QUALITY_QUALITY:0 "Kvalita"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE:0 "Ultra výkon"
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY:0 "Ultra kvalita"
 OPTION_UPSCALE_XESS:0 "Intel® XeSS"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Zobrazí hru v okně. Nastavení rozlišení mění velikost okna."
 OPTION_WINDOWED:0 "Okno"
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Váš e-mail Paradox účtu"
 SETTING_Ambient_TOOLTIP:0 "#T Hlasitost ambientu\n#!Nastavuje hlasitost environmentálního ambientu."
 SETTING_Ambient:0 "Ambience"
 SETTING_ANIMATION_SPEED:0 "Rychlost animace"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Deaktivováno"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Použití anisotropního filtrování učiní texturované povrchy vypadat lépe.\n\nNižší nastavení může zvýšit výkon."
 SETTING_ANISOTROPIC_FILTERING:0 "Filtraci textur"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Použití anti-aliasingu učiní hrany obrázků hladšími.\n\nDoporučuje se FXAA."
 SETTING_ANTI_ALIASING:0 "Antialiasing"
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Úroveň debug logu"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP:0 "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Vyberte zvukový profil, který vyhovuje vašemu nastavení."
 SETTING_AUDIO_DEVICE_PROFILE:0 "Zvukový profil"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mix upravený pro $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_HEADPHONES:0 "Sluchátka"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Zjemňuje zvuk pro noční hraní, ztlumí vyšší tóny a komprimuje dynamický rozsah."
 SETTING_AUDIO_OPTION_NIGHTMODE:0 "Noční režim"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Výchozí mix pro $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_SPEAKERS:0 "Reproduktory"
 SETTING_AUDIO_OPTION_TV_TOOLTIP:0 "#T $SETTING_AUDIO_OPTION_TV$\n#!Mix pro $SETTING_AUDIO_OPTION_TV$ a monitorové reproduktory."
 SETTING_AUDIO_OPTION_TV:0 "TV"
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Určuje, zda se automatická ukládání ukládají do cloudu nebo ne."
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Nastavuje, jak často se hra automaticky ukládá."
 SETTING_AUTOSAVE:0 "Interval automatického ukládání"
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Povolí efekt "bloom", kde velmi jasná světla přetékají do ostatních částí obrazu.\n\nVypnutí toho může zvýšit výkon."
 SETTING_BLOOM:0 "Bloom"
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Určuje, zda se kamera vždy otočí na sever, nebo ne."
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP:0 "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nRychlost otáčení kamery."
 SETTING_CAMERA_ROTATION_SPEED:1 "Rychlost otáčení kamery"
 SETTING_CAMERA_SPEED:0 "Rychlost kamery"
 SETTING_CAMERA_STRATEGY:0 "Typ kamery"
 SETTING_CAMERA_TILT:0 "Naklonění kamery"
 SETTING_CENTERED_ZOOM_IN:0 "Centrové přiblížení"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT:0 "Příkaz pro otevření kódového editoru"
 SETTING_COLOR_BLIND_MODE_TOOLTIP:0 "#T $SETTING_COLOR_BLIND_MODE$\n#!Změní barvy použité v textu po celé hře na sadu barev, které jsou snáze rozlišitelné pro různé typy barvocitné slepoty."
 SETTING_COLOR_BLIND_MODE:0 "Režim pro daltonisty"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND:0 "Úplné rozšíření, iterace pomocí klávesy tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND:0 "Částečné rozšíření, dokud nedojde k rozdílu"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE:0 "Režim automatického dokončování v konzoli"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Určuje, jak zobrazit hru na vaší obrazovce"
 SETTING_DISPLAY_MODE:0 "Režim zobrazení"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Pokud má váš počítač více monitorů, vyberte ten, který bude použit hrou."
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DOF_TOOLTIP:0 "#T $SETTING_DOF$\n#!Povolí hloubku ostrosti k simulaci objektivu kamery, rozmazává body mimo zaostření obrazu.\n\nVypnutí může zvýšit výkon."
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Příkaz pro otevření editoru"
 SETTING_EDITOR_POSTFIX:0 "Přípona editoru"
 SETTING_EDITOR:0 "Editor"
 SETTING_Effects:0 "Efekty"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Určuje, zda je neprostupný terén zahrnut v hranicích národa na mapě."
 SETTING_FRAMERATE_CAP_TOOLTIP:1 "#T $SETTING_FRAMERATE_CAP$#!\nMaximální FPS (snímků za sekundu), které hra vykreslí.\n\nNižší nastavení může snížit spotřebu energie."
 SETTING_FRAMERATE_CAP:1 "Maximální FPS"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:3 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Nastavuje kvalitu obrazu hry.\n\nNižší rozlišení může zvýšit výkon.\n\n#X Rozlišení hry s nepodporovaným poměrem stran může způsobit, že se rozhraní objeví mimo obrazovku#!"
 SETTING_FULLSCREEN_RESOLUTION:0 "Rozlišení"
 SETTING_GRACEFUL_EXIT:0 "Hladké ukončení"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Vybere, kterou grafickou kartu hra použije.\n\nPoužití integrované grafické karty nebo softwarového rendereru může snížit výkon."
 SETTING_GRAPHICS_DEVICE:0 "Grafická karta"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Nastavuje měřítko celé uživatelské rozhraní. Užitečné pro vyšší rozlišení obrazovky.\n\n#X Příliš vysoké nastavení může způsobit, že rozhraní se správně nevejde na obrazovku!#!"
 SETTING_GUI_SCALING:0 "Měřítko GUI"
 SETTING_INPUT_DEVICE:0 "Vstupní zařízení"
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nUrčuje jazyk uživatelského rozhraní."
 SETTING_LANGUAGE:0 "Jazyk"
 SETTING_LENS_FLARE_TOOLTIP:0 "#T $SETTING_LENS_FLARE$\n#!Povolí efekt odlesku, který se objevuje v oblastech s vysokým bloomingem. Bloom musí být povolen, aby se efekt objevil.\n\nVypnutí toho může zvýšit výkon."
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Zobrazit příkaz logu"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP:0 "Interval automatického ukládání editoru map (minuty)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES:0 "Automatické ukládání v editoru map (minuty)"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:1 "#T $SETTING_MAPOBJECT_QUALITY$#!\nUrčuje nejvyšší úroveň kvality mapových objektů (např. budov).\n\nNižší nastavení může zvýšit výkon."
 SETTING_MAP_SSAO_TOOLTIP:0 "#T $SETTING_MAP_SSAO$\n#!Určuje, zda má být na mapu aplikována ambientní okluze v prostoru obrazovky.\n\nVypnutí může zvýšit výkon."
 SETTING_Master_TOOLTIP:0 "#T Hlavní hlasitost\n#!Nastaví hlasitost všech zvuků ve hře."
 SETTING_Master:0 "Hlavní"
 SETTING_MESH_LOD_BIAS_TOOLTIP:1 "#T $SETTING_MESH_LOD_BIAS$#!\nUrčuje kvalitu LOD (úrovně detailů) na mapových objektech jako jsou modely jednotek.\n\nNižší nastavení může zvýšit výkon."
 SETTING_MESH_LOD_BIAS:0 "Kvalita LOD sítě"OPTION_UPSCALE_QUALITY_ULTRA_QUALITY:0 "Ultra kvalita"
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Pokud je zapnuto, 3D modely hladce přecházejí mezi různými úrovněmi detailů (LOD), když zoomujete dovnitř nebo ven.\n\nVypnutí toho může zvýšit výkon."
 SETTING_MESH_LOD_FADE:0 "Mizení LOD mřížky"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR:0 "Ignorovat kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR:0 "Relativní kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP:0 "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nJak se kamera chová v závislosti na kurzoru myši při přiblížení/oddálení."
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR:0 "Přiblížit na kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE:0 "Chování při zoomování"
 SETTING_MULTISAMPLING_DISABLED:0 "Vypnuto"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Použití vícenasobného vyhlazování (MSAA) učiní okraje obrázků hladšími.\n\nNižší nastavení může zvýšit výkon."
 SETTING_MULTI_SAMPLING:0 "Antialiasing (MSAA)"
 SETTING_MUSIC_DENSITY_TOOLTIP:0 "Ovládá rovnováhu mezi plnými písněmi, tichem a skladebami na pozadí.\n\nIntenzivní = Většinou písně hrající jedna po druhé, podobně jako 'rádio'.\nVyvážené = Perfektní vyvážení mezi písněmi, tichem a atmosférou.\nUvolněné = Většinou relaxační hudba, která poskytuje lepší zážitek z atmosféry a méně pocit repetice po několika hodinách hraní.”"
 SETTING_MUSIC_DENSITY:0 "Hustota hudby"
 SETTING_Music_TOOLTIP:0 "#T Hlasitost hudby\n#!Nastavuje hlasitost hudby."
 SETTING_Music:0 "Hudba"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE:0 "Režim panu myší v editoru uzlů"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED:0 "Vypnuto"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP:0 "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Použití vícero vzorkování pro Alpha-To-Coverage ke zjemnění přechodů vlasů.\n\nNižší nastavení zvyšují výkon."
 SETTING_PORTRAIT_MULTI_SAMPLING:0 "Portrét MultiSampling"
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Určuje, jak se názvy měst a provincií objevují na mapě."
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Vyberte přednastavení pokročilých grafických možností níže.\n\nNízké přednastavení zvýší výkon."
 SETTING_QUALITY:0 "Přednastavení kvality"
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nOvládá kvalitu vody refrakce, pokud jsou povoleny.\n\nNižší nastavení může zvýšit výkon."
 SETTING_REFRACTION_TOOLTIP:0 "Určuje, zda se na vodě objevují refrakce nebo ne."
 SETTING_RENDERER_TOOLTIP:0 "Určuje, který renderer se používá."
 SETTING_RENDERER:0 "Renderer"
 SETTING_RENDER_SCALE_FORMAT:0 "$VALUE|%0$"
 SETTING_RENDER_SCALE_TOOLTIP:0 "#T $SETTING_RENDER_SCALE$#!\nMěřítko rozlišení renderování hry ve srovnání s hlavním rozlišením, bez uživatelského rozhraní.\n\nNižší nastavení může zvýšit výkon, ale sníží celkovou věrnost, zatímco překročení 100% může zvýšit věrnost, ale pravděpodobně sníží výkon."
 SETTING_RENDER_SCALE:0 "Měřítko renderování"
 SETTINGS_CATEGORY_ACCESSIBILITY:0 "Přístupnost"
 SETTINGS_CATEGORY_GAME:0 "Hra"
 SETTINGS_CATEGORY_UI:0 "Rozhraní"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED:0 "Vypnuto"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE:0 "Volné"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP:0 "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nJak se chová kamera při panningu s myší."
 SETTING_SCREEN_EDGE_SCROLL_MODE:0 "Panování myší"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS:0 "8 směrů"
 SETTING_SCROLL_SPEED_TOOLTIP:0 "#T $SETTING_SCROLL_SPEED$#!\nNastavuje, jak rychle se mapa posouvá při používání klávesnice nebo myši."
 SETTING_SCROLL_SPEED:1 "Rychlost posunu"
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP:0 "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Povolí sekundární efekt odlesku, který se objevuje v oblastech s vysokým bloomingem. Bloom musí být povolen, aby se efekt objevil.\n\nVypnutí toho může zvýšit výkon."
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP:0 "#T $Rychlost přenosu souborů$\n#!Nastaví maximální rychlost přenosu souborů s uloženými hrami v multiplayerovém lobby.\n\nNižší nastavení může zlepšit stabilitu sítě při připojování k multiplayerovým hrám, ale má negativní vliv na doby načítání multiplayeru."
 SETTINGS_FILE_TRANSFER_SPEED:0 "Rychlost přenosu souborů"
 SETTING_SFX_TOOLTIP:0 "#T Hlasitost SFX\n#!Nastaví hlasitost zvukových efektů, jako je boj."
 SETTING_SFX:0 "SFX"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Určuje rozlišení, s jakým jsou vykreslovány stínové mapy, pokud jsou stíny povoleny.\n\nNižší nastavení může zvýšit výkon."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Kvalita stínů"
 SETTING_TERRAIN_SMOOTHING:1 "Hladění terénu"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nOvládá rozlišení načtených textur.\n\nNižší nastavení mohou zvýšit výkon."
 SETTING_TEXTURE_QUALITY:1 "Kvalita textur"
 SETTING_TEXTURE_STREAMING_CACHE:0 "Velikost cache pro streaming textur"SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Použití anti-aliasingu s vícero vzorky (MSAA) učiní hrany obrázků hladšími.\n\nNižší nastavení může zvýšit výkon."
 SETTING_TEXTURE_STREAMING_TOOLTIP:0 "#T $SETTING_TEXTURE_STREAMING$#!\nTextury se načítají podle potřeby.\n\nSnižuje využití paměti GPU na úkor některých CPU časových přetížení. Může zvýšit výkon pro GPU s malým množstvím paměti."
 SETTING_TEXTURE_STREAMING:0 "Streamování textur"
 SETTING_UI_TOOLTIP:0 "#T Hlasitost rozhraní\n#!Nastavuje hlasitost uživatelského rozhraní."
 SETTING_UI:0 "Rozhraní"
 SETTING_UPSCALE_QUALITY:0 "Kvalita zvětšení"
 SETTING_UPSCALE:0 "Metoda zvětšení"
 SETTING_VALUE_MB:0 "$VALUE$ MB"
 SETTING_VALUE_MINUTES:0 "$VALUE$ minut"
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ sekundy"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VO_TOOLTIP:0 "#T Hlasitost přednesu\n#!Nastavuje hlasitost zvuku přednesu ve hře."
 SETTING_VO:0 "Přednes"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Zajišťuje, aby hra a váš monitor měly stejnou snímkovou frekvenci, což snižuje trhání obrazu.\n\nVypnutí toho může zvýšit výkon."
 SETTING_VSYNC:0 "VSync"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:2 "#T $SETTING_WINDOWED_RESOLUTION$\n#!Nastavuje rozlišení herního okna, pokud je hra v oknovém režimu.\n\nMusí být ve formátu #b ČÍSLO#!x#b ČÍSLO#!.\n\n#X Herní rozlišení s nepodporovaným poměrem stran může způsobit, že se rozhraní objeví mimo obrazovku#!"
 SETTING_WINDOWED_RESOLUTION:0 "Rozlišení ve windowed režimu"
 SETTING_ZOOM_SPEED_TOOLTIP:0 "#T $SETTING_ZOOM_SPEED$#!\nRychlost zoomu kamery."
 SETTING_ZOOM_SPEED:1 "Rychlost zoomu"
