l_polish:
 CAMERA_FPS: "První osoba"
 CAMERA_TABLETOP: "Stůl"
 CAMERA_WASD: "Styl WASD"
 GAMEPAD: "Gamepad"
 MOUSE_AND_KEYBOARD: "Myš a klávesnice"
 NO_AUTOSAVE: "Žádné automatické ukládání"
 OPTION_ANTI_ALIASING_DISABLED: "Zakázáno"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CUSTOM: "Vlastní"
 OPTION_DEFAULT: "Výchozí"
 OPTION_DISABLED: "Zakázáno"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Zobrazí hru pomocí celé obrazovky. Nastavení rozlišení změní, jak ostrý bude obraz."
 OPTION_FULLSCREEN: "Celá obrazovka"
 OPTION_HIGH: "Vysoké"
 OPTION_LOW: "Nízké"
 OPTION_MEDIUM: "Střední"
 OPTION_OFF: "Vypnuto"
 OPTION_ULTRA: "Ultra"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_QUALITY_BALANCED: "Vyvážené"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Výkon"
 OPTION_UPSCALE_QUALITY_QUALITY: "Kvalita"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Ultra výkon"
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra kvalita"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Zobrazí hru v okně. Nastavení rozlišení mění velikost okna."
 OPTION_WINDOWED: "Okno"
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Váš e-mail Paradox účtu"
 SETTING_Ambient_TOOLTIP: "#T Hlasitost ambientu\n#!Nastavuje hlasitost environmentálního ambientu."
 SETTING_Ambient: "Ambience"
 SETTING_ANIMATION_SPEED: "Rychlost animace"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Deaktivováno"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Použití anisotropního filtrování učiní texturované povrchy vypadat lépe.\n\nNižší nastavení může zvýšit výkon."
 SETTING_ANISOTROPIC_FILTERING: "Filtraci textur"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Použití anti-aliasingu učiní hrany obrázků hladšími.\n\nDoporučuje se FXAA."
 SETTING_ANTI_ALIASING: "Antialiasing"
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Úroveň debug logu"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Vyberte zvukový profil, který vyhovuje vašemu nastavení."
 SETTING_AUDIO_DEVICE_PROFILE: "Zvukový profil"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mix upravený pro $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_HEADPHONES: "Sluchátka"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Zjemňuje zvuk pro noční hraní, ztlumí vyšší tóny a komprimuje dynamický rozsah."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Noční režim"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Výchozí mix pro $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_SPEAKERS: "Reproduktory"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Mix pro $SETTING_AUDIO_OPTION_TV$ a monitorové reproduktory."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Určuje, zda se automatická ukládání ukládají do cloudu nebo ne."
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Nastavuje, jak často se hra automaticky ukládá."
 SETTING_AUTOSAVE: "Interval automatického ukládání"
 SETTING_BLOOM_TOOLTIP: "#T $SETTING_BLOOM$\n#!Povolí efekt "bloom", kde velmi jasná světla přetékají do ostatních částí obrazu.\n\nVypnutí toho může zvýšit výkon."
 SETTING_BLOOM: "Bloom"
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Určuje, zda se kamera vždy otočí na sever, nebo ne."
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nRychlost otáčení kamery."
 SETTING_CAMERA_ROTATION_SPEED: "Rychlost otáčení kamery"
 SETTING_CAMERA_SPEED: "Rychlost kamery"
 SETTING_CAMERA_STRATEGY: "Typ kamery"
 SETTING_CAMERA_TILT: "Naklonění kamery"
 SETTING_CENTERED_ZOOM_IN: "Centrové přiblížení"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Příkaz pro otevření kódového editoru"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Změní barvy použité v textu po celé hře na sadu barev, které jsou snáze rozlišitelné pro různé typy barvocitné slepoty."
 SETTING_COLOR_BLIND_MODE: "Režim pro daltonisty"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Úplné rozšíření, iterace pomocí klávesy tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Částečné rozšíření, dokud nedojde k rozdílu"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Režim automatického dokončování v konzoli"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Určuje, jak zobrazit hru na vaší obrazovce"
 SETTING_DISPLAY_MODE: "Režim zobrazení"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Pokud má váš počítač více monitorů, vyberte ten, který bude použit hrou."
 SETTING_DISPLAY: "Monitor"
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Povolí hloubku ostrosti k simulaci objektivu kamery, rozmazává body mimo zaostření obrazu.\n\nVypnutí může zvýšit výkon."
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Příkaz pro otevření editoru"
 SETTING_EDITOR_POSTFIX: "Přípona editoru"
 SETTING_EDITOR: "Editor"
 SETTING_Effects: "Efekty"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Určuje, zda je neprostupný terén zahrnut v hranicích národa na mapě."
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nMaximální FPS (snímků za sekundu), které hra vykreslí.\n\nNižší nastavení může snížit spotřebu energie."
 SETTING_FRAMERATE_CAP: "Maximální FPS"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Nastavuje kvalitu obrazu hry.\n\nNižší rozlišení může zvýšit výkon.\n\n#X Rozlišení hry s nepodporovaným poměrem stran může způsobit, že se rozhraní objeví mimo obrazovku#!"
 SETTING_FULLSCREEN_RESOLUTION: "Rozlišení"
 SETTING_GRACEFUL_EXIT: "Hladké ukončení"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Vybere, kterou grafickou kartu hra použije.\n\nPoužití integrované grafické karty nebo softwarového rendereru může snížit výkon."
 SETTING_GRAPHICS_DEVICE: "Grafická karta"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Nastavuje měřítko celé uživatelské rozhraní. Užitečné pro vyšší rozlišení obrazovky.\n\n#X Příliš vysoké nastavení může způsobit, že rozhraní se správně nevejde na obrazovku!#!"
 SETTING_GUI_SCALING: "Měřítko GUI"
 SETTING_INPUT_DEVICE: "Vstupní zařízení"
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nUrčuje jazyk uživatelského rozhraní."
 SETTING_LANGUAGE: "Jazyk"
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Povolí efekt odlesku, který se objevuje v oblastech s vysokým bloomingem. Bloom musí být povolen, aby se efekt objevil.\n\nVypnutí toho může zvýšit výkon."
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Zobrazit příkaz logu"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Interval automatického ukládání editoru map (minuty)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Automatické ukládání v editoru map (minuty)"
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nUrčuje nejvyšší úroveň kvality mapových objektů (např. budov).\n\nNižší nastavení může zvýšit výkon."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Určuje, zda má být na mapu aplikována ambientní okluze v prostoru obrazovky.\n\nVypnutí může zvýšit výkon."
 SETTING_Master_TOOLTIP: "#T Hlavní hlasitost\n#!Nastaví hlasitost všech zvuků ve hře."
 SETTING_Master: "Hlavní"
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nUrčuje kvalitu LOD (úrovně detailů) na mapových objektech jako jsou modely jednotek.\n\nNižší nastavení může zvýšit výkon."
 SETTING_MESH_LOD_BIAS: "Kvalita LOD sítě"OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Ultra kvalita"
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Pokud je zapnuto, 3D modely hladce přecházejí mezi různými úrovněmi detailů (LOD), když zoomujete dovnitř nebo ven.\n\nVypnutí toho může zvýšit výkon."
 SETTING_MESH_LOD_FADE: "Mizení LOD mřížky"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignorovat kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Relativní kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nJak se kamera chová v závislosti na kurzoru myši při přiblížení/oddálení."
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Přiblížit na kurzor"
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Chování při zoomování"
 SETTING_MULTISAMPLING_DISABLED: "Vypnuto"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Použití vícenasobného vyhlazování (MSAA) učiní okraje obrázků hladšími.\n\nNižší nastavení může zvýšit výkon."
 SETTING_MULTI_SAMPLING: "Antialiasing (MSAA)"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Ovládá rovnováhu mezi plnými písněmi, tichem a skladebami na pozadí.\n\nIntenzivní = Většinou písně hrající jedna po druhé, podobně jako 'rádio'.\nVyvážené = Perfektní vyvážení mezi písněmi, tichem a atmosférou.\nUvolněné = Většinou relaxační hudba, která poskytuje lepší zážitek z atmosféry a méně pocit repetice po několika hodinách hraní.”"
 SETTING_MUSIC_DENSITY: "Hustota hudby"
 SETTING_Music_TOOLTIP: "#T Hlasitost hudby\n#!Nastavuje hlasitost hudby."
 SETTING_Music: "Hudba"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Režim panu myší v editoru uzlů"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Vypnuto"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Použití vícero vzorkování pro Alpha-To-Coverage ke zjemnění přechodů vlasů.\n\nNižší nastavení zvyšují výkon."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Portrét MultiSampling"
 SETTING_PROVINCE_NAMES_TOOLTIP: "Určuje, jak se názvy měst a provincií objevují na mapě."
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Vyberte přednastavení pokročilých grafických možností níže.\n\nNízké přednastavení zvýší výkon."
 SETTING_QUALITY: "Přednastavení kvality"
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nOvládá kvalitu vody refrakce, pokud jsou povoleny.\n\nNižší nastavení může zvýšit výkon."
 SETTING_REFRACTION_TOOLTIP: "Určuje, zda se na vodě objevují refrakce nebo ne."
 SETTING_RENDERER_TOOLTIP: "Určuje, který renderer se používá."
 SETTING_RENDERER: "Renderer"
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nMěřítko rozlišení renderování hry ve srovnání s hlavním rozlišením, bez uživatelského rozhraní.\n\nNižší nastavení může zvýšit výkon, ale sníží celkovou věrnost, zatímco překročení 100% může zvýšit věrnost, ale pravděpodobně sníží výkon."
 SETTING_RENDER_SCALE: "Měřítko renderování"
 SETTINGS_CATEGORY_ACCESSIBILITY: "Přístupnost"
 SETTINGS_CATEGORY_GAME: "Hra"
 SETTINGS_CATEGORY_UI: "Rozhraní"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Vypnuto"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Volné"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nJak se chová kamera při panningu s myší."
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Panování myší"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 směrů"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nNastavuje, jak rychle se mapa posouvá při používání klávesnice nebo myši."
 SETTING_SCROLL_SPEED: "Rychlost posunu"
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Povolí sekundární efekt odlesku, který se objevuje v oblastech s vysokým bloomingem. Bloom musí být povolen, aby se efekt objevil.\n\nVypnutí toho může zvýšit výkon."
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $Rychlost přenosu souborů$\n#!Nastaví maximální rychlost přenosu souborů s uloženými hrami v multiplayerovém lobby.\n\nNižší nastavení může zlepšit stabilitu sítě při připojování k multiplayerovým hrám, ale má negativní vliv na doby načítání multiplayeru."
 SETTINGS_FILE_TRANSFER_SPEED: "Rychlost přenosu souborů"
 SETTING_SFX_TOOLTIP: "#T Hlasitost SFX\n#!Nastaví hlasitost zvukových efektů, jako je boj."
 SETTING_SFX: "SFX"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Určuje rozlišení, s jakým jsou vykreslovány stínové mapy, pokud jsou stíny povoleny.\n\nNižší nastavení může zvýšit výkon."
 SETTING_SHADOW_MAP_RESOLUTION: "Kvalita stínů"
 SETTING_TERRAIN_SMOOTHING: "Hladění terénu"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nOvládá rozlišení načtených textur.\n\nNižší nastavení mohou zvýšit výkon."
 SETTING_TEXTURE_QUALITY: "Kvalita textur"
 SETTING_TEXTURE_STREAMING_CACHE: "Velikost cache pro streaming textur"SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Použití anti-aliasingu s vícero vzorky (MSAA) učiní hrany obrázků hladšími.\n\nNižší nastavení může zvýšit výkon."
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nTextury se načítají podle potřeby.\n\nSnižuje využití paměti GPU na úkor některých CPU časových přetížení. Může zvýšit výkon pro GPU s malým množstvím paměti."
 SETTING_TEXTURE_STREAMING: "Streamování textur"
 SETTING_UI_TOOLTIP: "#T Hlasitost rozhraní\n#!Nastavuje hlasitost uživatelského rozhraní."
 SETTING_UI: "Rozhraní"
 SETTING_UPSCALE_QUALITY: "Kvalita zvětšení"
 SETTING_UPSCALE: "Metoda zvětšení"
 SETTING_VALUE_MB: "$VALUE$ MB"
 SETTING_VALUE_MINUTES: "$VALUE$ minut"
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ sekundy"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VO_TOOLTIP: "#T Hlasitost přednesu\n#!Nastavuje hlasitost zvuku přednesu ve hře."
 SETTING_VO: "Přednes"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Zajišťuje, aby hra a váš monitor měly stejnou snímkovou frekvenci, což snižuje trhání obrazu.\n\nVypnutí toho může zvýšit výkon."
 SETTING_VSYNC: "VSync"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Nastavuje rozlišení herního okna, pokud je hra v oknovém režimu.\n\nMusí být ve formátu #b ČÍSLO#!x#b ČÍSLO#!.\n\n#X Herní rozlišení s nepodporovaným poměrem stran může způsobit, že se rozhraní objeví mimo obrazovku#!"
 SETTING_WINDOWED_RESOLUTION: "Rozlišení ve windowed režimu"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nRychlost zoomu kamery."
 SETTING_ZOOM_SPEED: "Rychlost zoomu"
