l_polish:
 MOD_ARTIFACT_DECAY_REDUCTION_ADD: "[artifact|E] Snížení rozpadu"
 MOD_ARTIFACT_DECAY_REDUCTION_MULT: "$MOD_ARTIFACT_DECAY_REDUCTION_ADD$"
 artifact_history_created_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_created_desc: "Vytvořeno [SelectLocalization( HISTORY_ENTRY.HasActor, HISTORY_ENTRY.GetActor.GetNameNoTooltip, 'UNKNOWN_BENEFACTOR' )] pro [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] v [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_stolen_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_stolen_desc: "Ukradeno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_created_before_history_title: "Unknown Creation"
 artifact_history_created_before_history_desc: "The details surrounding the creation of this artifact are unknown"
 artifact_history_given_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_given_desc: "Dáno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_inherited_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_inherited_desc: "Zděděno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_conquest_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_conquest_desc: "Vzato [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] ve válce proti [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_taken_in_siege_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_siege_desc: "Zabráno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] po obléhání [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_reforged_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_reforged_desc: "Přetvořeno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] v [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_discovered_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_discovered_desc: "Objeveno [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal] pro [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] v [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_claimed_by_house_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_claimed_by_house_desc: "Nárokováno [house|E] [HISTORY_ENTRY.GetActor.GetHouse.GetNameNoTooltip]"
 artifact_history_won_in_duel_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_won_in_duel_desc: "Vyhráno v duelu [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_taken_in_battle_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_battle_desc: "Zabráno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] v bitvě u [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_prize_created_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_prize_created_desc: "Nabídnuto [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] jako [GetActivityType( 'activity_tournament' ).GetName] [prize|E]"
 artifact_history_prize_awarded_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_prize_awarded_desc: "Oceněno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] jako [contest|E] [prize|E]"
 artifact_history_creator_discovered_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_creator_discovered_desc: "Zjistěno, že původně vytvořil [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_purchased_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_purchased_desc: "Zakoupeno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_ransomed_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_ransomed_desc: "Vykoupeno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 UNKNOWN_BENEFACTOR: "neznámý dobrodinec"
 ARTIFACT_DURABILITY: "Odolnost: $CURRENT|1$ / $MAX|1$"
 ARTIFACT_HISTORY: "Historie artefaktu"
 crown: "Koruna"
 helmet: "Pokrytí hlavy"
 miscellaneous: "$trinket$"
 miscellaneous_when_not_court: "$trinket$"
 regalia: "Regálie"
 journal: "Deník"
 weapon: "Zbraň"
 primary_armament: "$weapon$"
 armor: "Brnění"
 trinket: "Drobnůstka"
 trinket_1: "$trinket$"
 trinket_2: "$trinket$"
 trinket_3: "$trinket$"
 trinket_4: "$trinket$"
 artifact_slot_pedestal: "Předmět na podstavci"
 artifact_slot_helmet: "Pokrytí hlavy"
 artifact_slot_miscellaneous: "Drobnůstka"
 artifact_miscellaneous_when_not_court: "$miscellaneous_when_not_court$"
 artifact_slot_armor: "Brnění"
 artifact_slot_sculpture: "Nábytek"
 artifact_slot_primary_armament: "Zbraň"
 artifact_slot_throne: "Trůn"
 artifact_slot_wall_big: "Velká nástěnná ozdoba"
 artifact_slot_regalia: "Regálie"
 artifact_slot_wall_small: "Malá nástěnná ozdoba"
 artifact_slot_book: "Kniha"
 artifact_slot_journal: "Deník"
 artifact_crown: "Koruna"
 artifact_helmet: "Pokrytí hlavy"
 artifact_helmet_simple: "$artifact_helmet$"
 artifact_miscellaneous: "$trinket$"
 artifact_journal: "Deník"
 artifact_journal_simple: "$artifact_journal$"
 artifact_regalia: "Regálie"
 artifact_regalia_simple: "$regalia$"
 artifact_armor: "Brnění"
 artifact_trinket: "Drobnůstka"
 artifact_pedestal: "Předmět na podstavci"
 artifact_wall_big: "Velká nástěnná ozdoba"
 artifact_tapestry: "Tapiserie"
 artifact_sculpture: "Nábytek"
 artifact_scientific_apparatus: "Vědecký přístroj"
 artifact_wall_small: "Malá nástěnná ozdoba"
 artifact_animal_skull: "Lebka zvířete"
 artifact_animal_hide: "Zvířecí kůže"
 artifact_animal_hide_big: "Obrovská zvířecí kůže"
 artifact_throne: "Trůn"
 artifact_box: "Schránka"
 artifact_goblet: "Kalich"
 artifact_jug: "Džbán"
 artifact_book: "Kniha"
 artifact_panacea: "Panacea"
 artifact_elixir: "Elixír"
 artifact_philosophers_stone: "Kámen mudrců"
 artifact_sword: "meč"
 artifact_axe: "sekera"
 artifact_spear: "kopí"
 artifact_hammer: "kladivo"
 artifact_dagger: "dýka"
 artifact_mace: "palcát"
 artifact_armor_mail: "$armor$"
 artifact_armor_plate: "$armor$"
 artifact_armor_scale: "$armor$"
 artifact_armor_lamellar: "$armor$"
 artifact_armor_laminar: "$armor$"
 artifact_armor_brigandine: "$armor$"
 pedestal: "Podstavec"
 wall_big: "Velká nástěnná ozdoba"
 wall_small: "Malá nástěnná ozdoba"
 sculpture: "Nábytek"
 throne: "Trůn"
 book: "Kniha"
 wall_big_1: "$wall_big$"
 wall_big_2: "$wall_big$"
 wall_big_3: "$wall_big$"
 wall_small_1: "$wall_small$"
 wall_small_2: "$wall_small$"
 wall_small_3: "$wall_small$"
 sculpture_1: "$sculpture$"
 sculpture_2: "$sculpture$"
 lectern_1: "$book$"
 lectern_2: "$book$"
 lectern_3: "$book$"
 pedestal_1: "$pedestal$"
 pedestal_2: "$pedestal$"
 pedestal_3: "$pedestal$"
 pedestal_4: "$pedestal$"
 common: ""
 masterwork: "Mistrovské dílo"
 famed: "Proslulý"
 illustrious: "Význačný"
 legendary: "Legendární"
 rare: "Vzácný"
 REFORGE_ARTIFACT_TITLE: "Přetvořit artefakt"
 REFORGE: "Přetvořit"
 REFORGE_ARTIFACT: "#T $REFORGE_ARTIFACT_TITLE$#!"
 REPAIR_ARTIFACT_TITLE: "Opravit artefakt"
 REPAIR: "Opravit"
 REPAIR_ARTIFACT: "#T $REPAIR_ARTIFACT_TITLE$#!"
 EFFECTS_ON_ARTIFACT: "Účinky na [Artifact.GetName]"
 CHARACTER_PAYS_REFORGE_COST: "[CHARACTER.GetShortUIName|U] zaplatí $COST$ za přetvoření [ARTIFACT.GetName]"
 CHARACTER_PAYS_REPAIR_COST: "[CHARACTER.GetShortUIName|U] zaplatí $COST$ za opravu [ARTIFACT.GetName]"
 ARTIFACT_CHANGES_NAME: "[ARTIFACT.GetName] změní jméno na $NEW_NAME$"
 ARTIFACT_CHANGES_DESC: "[ARTIFACT.GetName] změní popis"
 ARTIFACT_CHANGES_VISUALS: "[ARTIFACT.GetName] změní vzhled"
 ARTIFACT_CHANGES_TYPE: "[ARTIFACT.GetName] se stane $NEW_TYPE$"
 ARTIFACT_CHANGES_RARITY: "[ARTIFACT.GetName] změní vzácnost a stane se $NEW_RARITY$"
 ARTIFACT_CHANGES_MODIFIER: "[ARTIFACT.GetName] poskytne tyto výhody:\n$NEW_MODIFIER$"
 ARTIFACT_CHANGES_TEMPLATE: "[ARTIFACT.GetName] bude $NEW_TEMPLATE$"
 ARTIFACT_CHANGES_DURABILITY: "[ARTIFACT.GetName] změní odolnost na $NEW_DURABILITY$ / $MAX_DURABILITY$"
 ARTIFACT_FULLY_REPAIRED: "[ARTIFACT.GetName] bude plně opraven a obnoven"
 NEW_ARTIFACT_TOOLTIP: "Toto je nově získaný [artifact|e]"
 ARTIFACT_RARITY_AND_TYPE: "[ARTIFACT.GetRarity] [ARTIFACT.GetType]"
 ARTIFACT_TYPE_ONLY: "[ARTIFACT.GetType]"
 ARTIFACT_RARITY_AND_SLOT_TYPE: "[ARTIFACT.GetRarity] [ARTIFACT.GetSlotType]"
 ARTIFACT_SLOT_TYPE_ONLY: "[ARTIFACT.GetSlotType]"
 INVENTORY_ARTIFACTS_SINGLE: "[inventory_artifact|E]"
 RENAME_ARTIFACT: "#T Přejmenovat artefakt#!"
 RENAME_ARTIFACT_TITLE: "Přejmenovat [ARTIFACT.GetNameNoTooltip]"
 RENAME_ARTIFACT_DESC: "Změnit jméno [ARTIFACT.GetNameNoTooltip]"
 RENAME_ARTIFACT_ACCEPT: "Potvrdit"
 ARTIFACT_CURRENT_HOLDER: "Současný vlastník: [Artifact.GetOwner.GetName]"
 ARTIFACT_CREATOR: "Tvůrce: [Artifact.GetCreator.GetName]"
 DETAILS_TAB_HISTORY: "Historie"
 DETAILS_TAB_CLAIMS: "Nárokovatelé"
 DETAILS_TAB_CLAIM_INTERACTIONS: "Máte nárok"
 DETAILS_TAB_NO_CLAIMANTS: "Na tento [artifact|E] nikdo nemá [artifact_claim|E]"
 CHARACTER_HAS_NO_ARTIFACTS: "Žádné [artifacts|E]"
 CHARACTER_HAS_NO_CLAIMED_ARTIFACTS: "Žádné [artifact_claims|E]"
 ARTIFACT_DETAILS_TITLE: "Podrobnosti artefaktu"
 ARTIFACT_DETAILS: "#T $ARTIFACT_DETAILS_TITLE$#!"
 ARTIFACT_SORTING_ALL_BUTTON: "Vše"
 created: "Vytvořeno"
 reforged: "Přetvořeno"
 given: "Darováno"
 stolen: "Ukradeno"
 conquest: "Dobyté"
 created_before_history: "Neznámý původ"
 inherited: "Zděděno"
 discovered: "Objeveno"
 taken_in_siege: "Dobyto při obléhání"
 won_in_duel: "Vyhráno v souboji"
 taken_in_battle: "Zabráno v bitvě"
 tournament_prize_creation: "Turnajová cena"
 tournament_prize_won: "Vyhráno v soutěži"
 CLAIMANT_ENTRY_HOUSE_HEAD: "Hlava rodu: [ClaimantEntry.GetHouse.GetHeadOfHouse.GetName]"
 ARTIFACT_YEARS_UNTIL_DECAY: "[Artifact.GetYearsUntilDecay] let"
 ARTIFACT_DURABILITY_TOOLTIP: "#T Odolnost#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nPři současné rychlosti úbytku tento [artifact|e] vydrží [ARTIFACT.GetYearsUntilDecay] let, než mu dojde [durability|E] a rozpadne se."
 ARTIFACT_DURABILITY_NO_DECAY_TOOLTIP: "#T Odolnost#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nTento [artifact|e] se momentálně nerozpadá a vydrží navždy, pokud nedojde ke ztrátě [durability|E]."
 DECAY_TOTAL: "Roční úbytek"
 DECAY_BASE: "Základní úbytek"
 CHARACTER_HAS_NO_VALID_SLOT: "@warning_icon! #X Žádné dostupné místo, které by pojalo [ARTIFACT.GetName]#!"
 SLOT_CANNOT_HOLD_ARTIFACT: "@warning_icon! #X $SLOT$ nemůže pojmout artefakty typu $TYPE$#!"
 EQUIP_ARTIFACT: "\n#I Kliknutím jej vybavíte#!"
 UNEQUIP_QUICK_TT: "#T Sejmout#!"
 EQUIP_ARTIFACT_REPLACE: "\n#I Kliknutím nahradíte $REPLACE_ARTIFACT$ tímto#!"
 SELECT_ARTIFACT: "Vybrat artefakt"
 ARTIFACT_ALREADY_EQUIPPED_IN_SLOT: "@warning_icon! #X [ARTIFACT.GetNameNoTooltip] je již vybaven v tomto slotu#!"
 INVENTORY_SLOT_TT: "#T [InventorySlot.GetName] pozice\n#![SelectLocalization( InventoryView.IsSelectedSlot( InventorySlot.Self ), 'SELECT_ARTIFACT_FOR_SLOT', 'SELECT_INVENTORY_SLOT' )]"
 SELECT_INVENTORY_SLOT: "#I Kliknutím zobrazíte artefakty [InventorySlot.GetName]#!"
 SELECT_ARTIFACT_FOR_SLOT: "#I Kliknutím zrušíte výběr#!"
 CHARACTER_CANNOT_DECLARE_WAR: "[Character.GetShortUINameNoTooltip|U] momentálně nemůže vyhlásit válku kvůli tomuto [artifact|e]"
 CHARACTER_CANNOT_DECLARE_WAR_SHORT: "Nelze vyhlásit válku"
 CHARACTER_CAN_DECLARE_WAR: "[Character.GetShortUINameNoTooltip|U] může vyhlásit válku kvůli tomuto [artifact|e]"
 DUEL_FOR_ARTIFACT_TOOLTIP: "#T Souboj o artefakt#!"
 ARTIFACT_SORT_ORDER_TOOLTIP: "#T Změnit řazení artefaktů#!"
 ARTIFACT_CLAIM_SORT_ORDER_TOOLTIP: "#T Změnit řazení [artifact_claim|e]#!"
 ARTIFACT_SORTING_TAB_TOOLTIP: "[InventorySlotType.GetName] [artifacts|e]"
 ARTIFACT_SORTING_TAB_ALL_TOOLTIP: "Všechny [artifacts|e]"
 acquisition_date: "Datum získání"
 creation_date: "Datum vzniku"
 type: "Typ"
 rarity: "Vzácnost"
 name: "Jméno"
 durability: "Odolnost"
 artifact_type: "Typ artefaktu"
 claim_type: "Typ nároku"
 UNEQUIP_ARTIFACT: "\n#I Kliknutím jej sejměte#!"
 ARTIFACT_EQUIPPED_TOOLTIP: "#T [artifact|e] je vybavený#!"
 ARTIFACT_AT_MAX_DURABILITY: "@warning_icon! #X [ARTIFACT.GetNameNoTooltip] je již na maximální odolnosti#!"
 IMMINENT_HOUSE_CLAIMANT: "[Artifact.GetOwner.GetHouse.GetName] #low ( [Artifact.GetYearsUntilHouseClaim( Artifact.GetOwner.Self )] let )#!"
 HOUSE_CLAIMS: "#help Nároky rodu:#!"
 DECAY_ARTIFACT_EQUIPPED: "Vybavené"
 DECAY_ARTIFACT_DISPlAY: "Vystaveno"
 DECAY_ARTIFACT_UNEQUIPPED: "Uloženo"
 DISPLAY_ARTIFACT: "#I \nKliknutím vystavíte#!"
 PUT_COURT_ARTIFACT_ON_DISPLAY: "#I \nKliknutím zde vystavíte#!"
 REMOVE_COURT_ARTIFACT_FROM_DISPLAY: "#I \nKliknutím uložíte#!"
 MOVE_COURT_ARTIFACT_TO_DISPLAY: "#I \nKliknutím sem přesunete#!"
 COURT_ARTIFACT_ON_DISPLAY: "#T [court_artifact|e] je vystavený#!"
 ROYAL_COURT: "Královský dvůr"
 ARTIFACT_STORAGE: "Všechny dvorní artefakty"
 ARTIFACT_CLAIMS: "Nároky na artefakty"
 NEW_ARTIFACT: "#V Nové#!"
 EQUIPPED_ARTIFACT: "[Select_CString( Artifact.IsCourtArtifact, 'Displayed', 'Equipped' )] [Inventory.GetEquippedSlotOfMaxSlotText( Artifact.Self )]"
 GIFT_EQUIPPED_ARTIFACT: "[Select_CString( Artifact.IsCourtArtifact, 'Displayed', 'Equipped' )]"
 CHARACTER_WITHOUT_ROYAL_COURT_COURT_ARTIFACT_TAB: "Jelikož [Character.GetShortUIName] [Character.LocalPlayerString( 'have', 'has' )] žádný [royal_court|e], [Character.GetShortUIName] [Character.LocalPlayerString( 'have', 'has' )] nemá kde vystavit tyto [court_artifacts|e]."
 ARTIFACT_TITLE_ASSOCIATION: "Zděděno společně s [Artifact.GetAssociatedTitle.GetNameWithUnderlying]"
 EMPTY_INVENTORY_TOOLTIP: "@warning_icon! #X Nelze zobrazit inventář – nejsou zde žádné [artifacts|e] ani [artifact_claims|e] k zobrazení#!"
 ARTIFACT_PERSONAL_CLAIM: "Osobní nárok"
 ARTIFACT_HOUSE_CLAIM: "Rodový nárok"
 REFORGE_ARTIFACT_COMPLETELY: "Přetvořit [ARTIFACT.GetNameNoTooltip] na $NEW_TYPE$"
 REFORGE_COST: "Cena přetvoření: $COST$"
 REPAIR_COST: "Cena opravy: $COST$"
 CANNOT_REFORGE_WITHOUT_ANTIQUARIAN: "@warning_icon! #X Nelze přetvořit [artifacts|e] bez $antiquarian_court_position$#!"
 ARTIFACT_FALLBACK_EFFECT: "#S Pokud nesplníte požadavky:#!\n[Artifact.GetFallbackEffects]"
 ARTIFACT_EFFECT: "[SelectLocalization( Artifact.HasCanBenefit, 'ARTIFACT_EFFECT_HAS_CAN_BENEFIT', '' )][Artifact.GetModifierEffects]"
 ARTIFACT_EFFECT_HAS_CAN_BENEFIT: "#S Pokud splníte #TOOLTIP:ARTIFACT_EFFECT_REQUIREMENT_TT #L Požadavky#!#!:#!\n"
 ARTIFACT_EFFECT_REQUIREMENT_TT: "[Artifact.GetCanBenefitPlayerDesc]"
 artifact_bowl: "Miska"
 artifact_plate: "Talíř"
 artifact_urn: "Urna"
 artifact_tun_barrel: "Vinný sud"
