l_polish:
 MOD_ARTIFACT_DECAY_REDUCTION_ADD: "[Concept('artifact','Artefakt')|E] – snížení chátrání"
 MOD_ARTIFACT_DECAY_REDUCTION_MULT: "$MOD_ARTIFACT_DECAY_REDUCTION_ADD$"
 artifact_history_created_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_created_desc: "Vytvořeno pro [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] v [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]; tvůrce: [SelectLocalization( HISTORY_ENTRY.HasActor, HISTORY_ENTRY.GetActor.GetNameNoTooltip, 'UNKNOWN_BENEFACTOR' )]"
 artifact_history_stolen_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_stolen_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'ukradla','ukradl')]"
 artifact_history_created_before_history_title: "Neznámý původ"
 artifact_history_created_before_history_desc: "Podrobnosti o vzniku tohoto artefaktu nejsou známy"
 artifact_history_given_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_given_desc: "Darováno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_inherited_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_inherited_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'zdědila','zdědil')]"
 artifact_history_conquest_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_conquest_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'získala','získal')] ve válce proti [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_taken_in_siege_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_siege_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'ukořistila','ukořistil')] po obléhání [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_reforged_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_reforged_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] nechal artefakt překovat v [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_discovered_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_discovered_desc: "Objeveno postavou [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal] pro [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] v [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_claimed_by_house_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_claimed_by_house_desc: "[Concept('house','Rod')|E] [HISTORY_ENTRY.GetActor.GetHouse.GetNameNoTooltip] vznesl na artefakt nárok"
 artifact_history_won_in_duel_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_won_in_duel_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'vyhrála','vyhrál')] v duelu"
 artifact_history_taken_in_battle_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_battle_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'ukořistila','ukořistil')] v bitvě u [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_prize_created_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_prize_created_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'nabídla','nabídl')] jako [Concept('prize','cenu')|E] v rámci [GetActivityType( 'activity_tournament' ).GetName]"
 artifact_history_prize_awarded_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_prize_awarded_desc: "Uděleno [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] jako [Concept('prize','cena')|E] za [Concept('contest','soutěž')|E]"
 artifact_history_creator_discovered_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_creator_discovered_desc: "Odhaleno, že původním tvůrcem byl [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_purchased_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_purchased_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'zakoupila','zakoupil')]"
 artifact_history_ransomed_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_ransomed_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] artefakt [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale,'vykoupila','vykoupil')]"
 UNKNOWN_BENEFACTOR: "neznámý dobrodinec"
 ARTIFACT_DURABILITY: "Trvanlivost: $CURRENT|1$ / $MAX|1$"
 ARTIFACT_HISTORY: "Historie artefaktu"
 crown: "Koruna"
 helmet: "Pokrývka hlavy"
 miscellaneous: "$trinket$"
 miscellaneous_when_not_court: "$trinket$"
 regalia: "Regálie"
 journal: "Deník"
 weapon: "Zbraň"
 primary_armament: "$weapon$"
 armor: "Zbroj"
 trinket: "Cetka"
 trinket_1: "$trinket$"
 trinket_2: "$trinket$"
 trinket_3: "$trinket$"
 trinket_4: "$trinket$"
 artifact_slot_pedestal: "Předmět na podstavci"
 artifact_slot_helmet: "Pokrývka hlavy"
 artifact_slot_miscellaneous: "Cetka"
 artifact_miscellaneous_when_not_court: "$miscellaneous_when_not_court$"
 artifact_slot_armor: "Zbroj"
 artifact_slot_sculpture: "Nábytek"
 artifact_slot_primary_armament: "Zbraň"
 artifact_slot_throne: "Trůn"
 artifact_slot_wall_big: "Velká nástěnná ozdoba"
 artifact_slot_regalia: "Regálie"
 artifact_slot_wall_small: "Malá nástěnná ozdoba"
 artifact_slot_book: "Kniha"
 artifact_slot_journal: "Deník"
 artifact_crown: "Koruna"
 artifact_helmet: "Pokrývka hlavy"
 artifact_helmet_simple: "$artifact_helmet$"
 artifact_miscellaneous: "$trinket$"
 artifact_journal: "Deník"
 artifact_journal_simple: "$artifact_journal$"
 artifact_regalia: "Regálie"
 artifact_regalia_simple: "$regalia$"
 artifact_armor: "Zbroj"
 artifact_trinket: "Cetka"
 artifact_pedestal: "Předmět na podstavci"
 artifact_wall_big: "Velká nástěnná ozdoba"
 artifact_tapestry: "Tapiserie"
 artifact_sculpture: "Nábytek"
 artifact_scientific_apparatus: "Vědecký přístroj"
 artifact_wall_small: "Malá nástěnná ozdoba"
 artifact_animal_skull: "Zvířecí lebka"
 artifact_animal_hide: "Zvířecí kožešina"
 artifact_animal_hide_big: "Obrovská zvířecí kožešina"
 artifact_throne: "Trůn"
 artifact_box: "Schránka"
 artifact_goblet: "Pohár"
 artifact_jug: "Džbán"
 artifact_book: "Kniha"
 artifact_panacea: "Všelék"
 artifact_elixir: "Elixír"
 artifact_philosophers_stone: "Kámen mudrců"
 artifact_sword: "meč"
 artifact_axe: "sekera"
 artifact_spear: "kopí"
 artifact_hammer: "kladivo"
 artifact_dagger: "dýka"
 artifact_mace: "palcát"
 artifact_armor_mail: "$armor$"
 artifact_armor_plate: "$armor$"
 artifact_armor_scale: "$armor$"
 artifact_armor_lamellar: "$armor$"
 artifact_armor_laminar: "$armor$"
 artifact_armor_brigandine: "$armor$"
 pedestal: "Podstavec"
 wall_big: "Velká nástěnná ozdoba"
 wall_small: "Malá nástěnná ozdoba"
 sculpture: "Nábytek"
 throne: "Trůn"
 book: "Kniha"
 wall_big_1: "$wall_big$"
 wall_big_2: "$wall_big$"
 wall_big_3: "$wall_big$"
 wall_small_1: "$wall_small$"
 wall_small_2: "$wall_small$"
 wall_small_3: "$wall_small$"
 sculpture_1: "$sculpture$"
 sculpture_2: "$sculpture$"
 lectern_1: "$book$"
 lectern_2: "$book$"
 lectern_3: "$book$"
 pedestal_1: "$pedestal$"
 pedestal_2: "$pedestal$"
 pedestal_3: "$pedestal$"
 pedestal_4: "$pedestal$"
 common: ""
 masterwork: "Mistrovské"
 famed: "Proslulé"
 illustrious: "Věhlasné"
 legendary: "Legendární"
 rare: "Vzácné"
 REFORGE_ARTIFACT_TITLE: "Překování artefaktu"
 REFORGE: "Překovat"
 REFORGE_ARTIFACT: "#T $REFORGE_ARTIFACT_TITLE$#!"
 REPAIR_ARTIFACT_TITLE: "Oprava artefaktu"
 REPAIR: "Opravit"
 REPAIR_ARTIFACT: "#T $REPAIR_ARTIFACT_TITLE$#!"
 EFFECTS_ON_ARTIFACT: "Účinky na [Artifact.GetName]"
 CHARACTER_PAYS_REFORGE_COST: "[CHARACTER.GetShortUIName|U] zaplatí $COST$ za překování [ARTIFACT.GetName]"
 CHARACTER_PAYS_REPAIR_COST: "[CHARACTER.GetShortUIName|U] zaplatí $COST$ za opravu [ARTIFACT.GetName]"
 ARTIFACT_CHANGES_NAME: "Název [ARTIFACT.GetName] se změní na $NEW_NAME$"
 ARTIFACT_CHANGES_DESC: "Popis [ARTIFACT.GetName] se změní"
 ARTIFACT_CHANGES_VISUALS: "Vzhled [ARTIFACT.GetName] se změní"
 ARTIFACT_CHANGES_TYPE: "Typ [ARTIFACT.GetName] se změní na $NEW_TYPE$"
 ARTIFACT_CHANGES_RARITY: "Vzácnost [ARTIFACT.GetName] se změní na $NEW_RARITY$"
 ARTIFACT_CHANGES_MODIFIER: "[ARTIFACT.GetName] poskytne následující výhody:\n$NEW_MODIFIER$"
 ARTIFACT_CHANGES_TEMPLATE: "[ARTIFACT.GetName] bude používat šablonu $NEW_TEMPLATE$"
 ARTIFACT_CHANGES_DURABILITY: "Trvanlivost [ARTIFACT.GetName] se změní na $NEW_DURABILITY$ / $MAX_DURABILITY$"
 ARTIFACT_FULLY_REPAIRED: "Proběhne úplná oprava a obnova artefaktu [ARTIFACT.GetName]"
 NEW_ARTIFACT_TOOLTIP: "Toto je nově získaný [Concept('artifact','artefakt')|e]"
 ARTIFACT_RARITY_AND_TYPE: "[ARTIFACT.GetType] – [ARTIFACT.GetRarity]"
 ARTIFACT_TYPE_ONLY: "[ARTIFACT.GetType]"
 ARTIFACT_RARITY_AND_SLOT_TYPE: "[ARTIFACT.GetSlotType] – [ARTIFACT.GetRarity]"
 ARTIFACT_SLOT_TYPE_ONLY: "[ARTIFACT.GetSlotType]"
 INVENTORY_ARTIFACTS_SINGLE: "[Concept('inventory_artifact','Osobní artefakt')|E]"
 RENAME_ARTIFACT: "#T Přejmenovat artefakt#!"
 RENAME_ARTIFACT_TITLE: "Přejmenovat [ARTIFACT.GetNameNoTooltip]"
 RENAME_ARTIFACT_DESC: "Změnit název [ARTIFACT.GetNameNoTooltip]"
 RENAME_ARTIFACT_ACCEPT: "Přijmout"
 ARTIFACT_CURRENT_HOLDER: "Současný držitel: [Artifact.GetOwner.GetName]"
 ARTIFACT_CREATOR: "Tvůrce: [Artifact.GetCreator.GetName]"
 DETAILS_TAB_HISTORY: "Historie"
 DETAILS_TAB_CLAIMS: "Nárokovatelé"
 DETAILS_TAB_CLAIM_INTERACTIONS: "Máš nárok"
 DETAILS_TAB_NO_CLAIMANTS: "Na tento [Concept('artifact','artefakt')|E] nemá nikdo [Concept('artifact_claim','nárok')|E]"
 CHARACTER_HAS_NO_ARTIFACTS: "Žádné [Concept('artifacts','artefakty')|E]"
 CHARACTER_HAS_NO_CLAIMED_ARTIFACTS: "Žádné [Concept('artifact_claims','nároky na artefakt')|E]"
 ARTIFACT_DETAILS_TITLE: "Podrobnosti artefaktu"
 ARTIFACT_DETAILS: "#T $ARTIFACT_DETAILS_TITLE$#!"
 ARTIFACT_SORTING_ALL_BUTTON: "Vše"
 created: "Vytvořeno"
 reforged: "Překováno"
 given: "Darováno"
 stolen: "Ukradeno"
 conquest: "Získáno dobytím"
 created_before_history: "Neznámý původ"
 inherited: "Zděděno"
 discovered: "Objeveno"
 taken_in_siege: "Ukořistěno při obléhání"
 won_in_duel: "Vyhráno v duelu"
 taken_in_battle: "Ukořistěno v bitvě"
 tournament_prize_creation: "Turnajová cena"
 tournament_prize_won: "Vyhráno v soutěži"
 CLAIMANT_ENTRY_HOUSE_HEAD: "Hlava rodu: [ClaimantEntry.GetHouse.GetHeadOfHouse.GetName]"
 ARTIFACT_YEARS_UNTIL_DECAY: "[Artifact.GetYearsUntilDecay] let"
 ARTIFACT_DURABILITY_TOOLTIP: "#T Trvanlivost#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nPři současné rychlosti chátrání vydrží tento [Concept('artifact','artefakt')|e] ještě [ARTIFACT.GetYearsUntilDecay] let, než zcela ztratí [Concept('durability','trvanlivost')|E] a rozbije se."
 ARTIFACT_DURABILITY_NO_DECAY_TOOLTIP: "#T Trvanlivost#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nTento [Concept('artifact','artefakt')|e] v současnosti nechátrá a vydrží navždy, pokud něco nezpůsobí ztrátu jeho [Concept('durability','trvanlivosti')|E]."
 DECAY_TOTAL: "Roční chátrání"
 DECAY_BASE: "Základní chátrání"
 CHARACTER_HAS_NO_VALID_SLOT: "@warning_icon! #X Není k dispozici žádný slot, do kterého lze umístit [ARTIFACT.GetName]#!"
 SLOT_CANNOT_HOLD_ARTIFACT: "@warning_icon! #X Do slotu $SLOT$ nelze umístit artefakty typu $TYPE$#!"
 EQUIP_ARTIFACT: "\n#I Kliknutím vybavíš tento artefakt#!"
 UNEQUIP_QUICK_TT: "#T Odebrat z výbavy#!"
 EQUIP_ARTIFACT_REPLACE: "\n#I Kliknutím tímto artefaktem nahradíš $REPLACE_ARTIFACT$#!"
 SELECT_ARTIFACT: "Vybrat artefakt"
 ARTIFACT_ALREADY_EQUIPPED_IN_SLOT: "@warning_icon! #X [ARTIFACT.GetNameNoTooltip] je již vybaven v tomto slotu#!"
 INVENTORY_SLOT_TT: "#T Slot: [InventorySlot.GetName]\n#![SelectLocalization( InventoryView.IsSelectedSlot( InventorySlot.Self ), 'SELECT_ARTIFACT_FOR_SLOT', 'SELECT_INVENTORY_SLOT' )]"
 SELECT_INVENTORY_SLOT: "#I Kliknutím zobrazíš artefakty pro slot [InventorySlot.GetName]#!"
 SELECT_ARTIFACT_FOR_SLOT: "#I Kliknutím zrušíš výběr#!"
 CHARACTER_CANNOT_DECLARE_WAR: "[Character.GetShortUINameNoTooltip|U] nyní nemůže vyhlásit válku o tento [Concept('artifact','artefakt')|e]"
 CHARACTER_CANNOT_DECLARE_WAR_SHORT: "Nelze vyhlásit válku"
 CHARACTER_CAN_DECLARE_WAR: "[Character.GetShortUINameNoTooltip|U] může vyhlásit válku o tento [Concept('artifact','artefakt')|e]"
 DUEL_FOR_ARTIFACT_TOOLTIP: "#T Duel o artefakt#!"
 ARTIFACT_SORT_ORDER_TOOLTIP: "#T Změnit řazení artefaktů#!"
 ARTIFACT_CLAIM_SORT_ORDER_TOOLTIP: "#T Změnit řazení [Concept('artifact_claim','nároků na artefakt')|e]#!"
 ARTIFACT_SORTING_TAB_TOOLTIP: "[Concept('artifacts','Artefakty')|e]: [InventorySlotType.GetName]"
 ARTIFACT_SORTING_TAB_ALL_TOOLTIP: "Všechny [Concept('artifacts','artefakty')|e]"
 acquisition_date: "Datum získání"
 creation_date: "Datum vytvoření"
 type: "Typ"
 rarity: "Vzácnost"
 name: "Název"
 durability: "Trvanlivost"
 artifact_type: "Typ artefaktu"
 claim_type: "Typ nároku"
 UNEQUIP_ARTIFACT: "\n#I Kliknutím odebereš tento artefakt z výbavy#!"
 ARTIFACT_EQUIPPED_TOOLTIP: "#T [Concept('artifact','Artefakt')|e] je ve výbavě#!"
 ARTIFACT_AT_MAX_DURABILITY: "@warning_icon! #X [ARTIFACT.GetNameNoTooltip] již má maximální trvanlivost#!"
 IMMINENT_HOUSE_CLAIMANT: "[Artifact.GetOwner.GetHouse.GetName] #low ( [Artifact.GetYearsUntilHouseClaim( Artifact.GetOwner.Self )] let )#!"
 HOUSE_CLAIMS: "#help Rodové nároky:#!"
 DECAY_ARTIFACT_EQUIPPED: "Ve výbavě"
 DECAY_ARTIFACT_DISPlAY: "Vystaveno"
 DECAY_ARTIFACT_UNEQUIPPED: "V úschově"
 DISPLAY_ARTIFACT: "#I \nKliknutím vystavíš#!"
 PUT_COURT_ARTIFACT_ON_DISPLAY: "#I \nKliknutím zde vystavíš#!"
 REMOVE_COURT_ARTIFACT_FROM_DISPLAY: "#I \nKliknutím uložíš#!"
 MOVE_COURT_ARTIFACT_TO_DISPLAY: "#I \nKliknutím sem přesuneš#!"
 COURT_ARTIFACT_ON_DISPLAY: "#T [Concept('court_artifact','Dvorský artefakt')|e] je vystaven#!"
 ROYAL_COURT: "Královský dvůr"
 ARTIFACT_STORAGE: "Všechny dvorské artefakty"
 ARTIFACT_CLAIMS: "Nároky na artefakty"
 NEW_ARTIFACT: "#V Nové#!"
 EQUIPPED_ARTIFACT: "[Select_CString( Artifact.IsCourtArtifact, 'Vystaveno', 'Ve výbavě' )] [Inventory.GetEquippedSlotOfMaxSlotText( Artifact.Self )]"
 GIFT_EQUIPPED_ARTIFACT: "[Select_CString( Artifact.IsCourtArtifact, 'Vystaveno', 'Ve výbavě' )]"
 CHARACTER_WITHOUT_ROYAL_COURT_COURT_ARTIFACT_TAB: "Protože [Character.GetShortUIName] [Character.LocalPlayerString( 'nemáš', 'nemá' )] žádný [Concept('royal_court','Královský dvůr')|e], [Character.GetShortUIName] [Character.LocalPlayerString( 'nemáš', 'nemá' )] kde tyto [Concept('court_artifacts','dvorské artefakty')|e] vystavit."
 ARTIFACT_TITLE_ASSOCIATION: "Zděděno spolu s [Artifact.GetAssociatedTitle.GetNameWithUnderlying]"
 EMPTY_INVENTORY_TOOLTIP: "@warning_icon! #X Inventář nelze zobrazit, protože neobsahuje žádné [Concept('artifacts','artefakty')|e] ani [Concept('artifact_claims','nároky na artefakt')|e]#!"
 ARTIFACT_PERSONAL_CLAIM: "Osobní nárok"
 ARTIFACT_HOUSE_CLAIM: "Rodový nárok"
 REFORGE_ARTIFACT_COMPLETELY: "Překovat [ARTIFACT.GetNameNoTooltip] na typ $NEW_TYPE$"
 REFORGE_COST: "Cena překování: $COST$"
 REPAIR_COST: "Cena opravy: $COST$"
 CANNOT_REFORGE_WITHOUT_ANTIQUARIAN: "@warning_icon! #X Překování [Concept('artifacts','artefaktů')|e] vyžaduje: $antiquarian_court_position$#!"
 ARTIFACT_FALLBACK_EFFECT: "#S Pokud nesplňuješ požadavky:#!\n[Artifact.GetFallbackEffects]"
 ARTIFACT_EFFECT: "[SelectLocalization( Artifact.HasCanBenefit, 'ARTIFACT_EFFECT_HAS_CAN_BENEFIT', '' )][Artifact.GetModifierEffects]"
 ARTIFACT_EFFECT_HAS_CAN_BENEFIT: "#S Pokud splňuješ #TOOLTIP:ARTIFACT_EFFECT_REQUIREMENT_TT #L požadavky#!#!:#!\n"
 ARTIFACT_EFFECT_REQUIREMENT_TT: "[Artifact.GetCanBenefitPlayerDesc]"
 artifact_bowl: "Miska"
 artifact_plate: "Talíř"
 artifact_urn: "Urna"
 artifact_tun_barrel: "Sud na víno"
