l_polish:
 OPTION_HALFYEAR:0 "Každých půl roku"
 SETTINGS_CATEGORY_QUALITY:0 "Kvalita"
 REQUIRE_RESTART_DESCRIPTION:0 "Některá nastavení nebudou mít účinek, dokud hru nepřenesete."
 OPTION_MONTHLY:0 "Každý měsíc"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE:0 "Uložit profil"
 SETTINGS_CATEGORY_ACCOUNT:0 "Účet"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_CATEGORY_SYSTEM:0 "Systém"
 SETTINGS_PAGE_SYSTEM:0 "Systém"
 SETTINGS_CATEGORY_AUDIO:0 "Zvuk"
 APPLY:0 "Použít"
 SETTINGS_INPUT_BINDING_WARNING_TEXT:0 "Upozornění: Toto vazba pro vstup již existuje pro '$INPUT_ACTION$'!\nStisknutím '$SETTINGS_INPUT_CONFIRM$' vymažete starou vazbu"
 SETTINGS_CATEGORY_CONTROLS:0 "Ovládání"
 SETTINGS_INPUT_BINDING_TEXT:0 "Prosím, vyberte vazbu pro akci '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 OPTION_YEARLY:0 "Každý rok"
 OPTION_FIVE_YEAR:0 "Každých pět let"
 SETTINGS_PAGE_GAME:0 "Hra"
 SETTINGS_PAGE_CONTROLS:0 "Ovládání"
 OPTION_NEVER:0 "Nikdy"
 REQUIRES_RESTART:0 "Vyžaduje restart"
 SETTINGS_INPUT_CLEAR:0 "Vymazat"
 SETTINGS_INPUT_REMAP_INPUT:0 "Pře mapovat vstup"
 SETTINGS_PAGE_INTERFACE:0 "Rozhraní"
 SETTINGS_INPUT_CONFIRM:0 "Potvrdit"
 SETTINGS_CATEGORY_SCREEN:0 "Obrazovka"
 OPTION_EASY:0 "Snadné"
 SETTINGS_PAGE_GRAPHICS:0 "Grafika"
 SETTINGS_INPUT_CANCEL:0 "Zrušit"
 OPTION_NORMAL:0 "Normální"
 SETTINGS_PAGE_AUDIO:0 "Zvuk"
 DISCARD:0 "Zahodit"
 SETTINGS_INPUT_RESET_INPUT_PROFILE:0 "Obnovit na výchozí hodnoty"
 OPTION_HARD:0 "Těžké"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE:0 "Načíst profil"
 SETTINGS_CATEGORY_INPUT_BINDINGS:0 "Vazby vstupu"
 SETTINGS_CATEGORY_CAMERA:0 "Kamera"
 SETTINGS:0 "Nastavení"
 OPTION_NO_AUTOSAVE:0 "Nevytvářet automatické úložiště"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS_CATEGORY_GUI:0 "GUI"
