l_polish:
 APPLY: "Použít"
 DISCARD: "Zahodit"
 OPTION_EASY: "Snadné"
 OPTION_FIVE_YEAR: "Každých pět let"
 OPTION_HALFYEAR: "Každých půl roku"
 OPTION_HARD: "Těžké"
 OPTION_MONTHLY: "Každý měsíc"
 OPTION_NEVER: "Nikdy"
 OPTION_NO_AUTOSAVE: "Nevytvářet automatické úložiště"
 OPTION_NORMAL: "Normální"
 OPTION_YEARLY: "Každý rok"
 REQUIRE_RESTART_DESCRIPTION: "Některá nastavení nebudou mít účinek, dokud hru nepřenesete."
 REQUIRES_RESTART: "Vyžaduje restart"
 SAVE_AND_CLOSE: "OK"
 SETTINGS_CATEGORY_ACCOUNT: "Účet"
 SETTINGS_CATEGORY_AUDIO: "Zvuk"
 SETTINGS_CATEGORY_CAMERA: "Kamera"
 SETTINGS_CATEGORY_CONTROLS: "Ovládání"
 SETTINGS_CATEGORY_GUI: "GUI"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Vazby vstupu"
 SETTINGS_CATEGORY_QUALITY: "Kvalita"
 SETTINGS_CATEGORY_SCREEN: "Obrazovka"
 SETTINGS_CATEGORY_SYSTEM: "Systém"
 SETTINGS_INPUT_BINDING_TEXT: "Prosím, vyberte vazbu pro akci '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Upozornění: Toto vazba pro vstup již existuje pro '$INPUT_ACTION$'!\nStisknutím '$SETTINGS_INPUT_CONFIRM$' vymažete starou vazbu"
 SETTINGS_INPUT_CANCEL: "Zrušit"
 SETTINGS_INPUT_CLEAR: "Vymazat"
 SETTINGS_INPUT_CONFIRM: "Potvrdit"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Načíst profil"
 SETTINGS_INPUT_REMAP_INPUT: "Pře mapovat vstup"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Obnovit na výchozí hodnoty"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Uložit profil"
 SETTINGS_PAGE_AUDIO: "Zvuk"
 SETTINGS_PAGE_CONTROLS: "Ovládání"
 SETTINGS_PAGE_EDITOR: "Editor"
 SETTINGS_PAGE_GAME: "Hra"
 SETTINGS_PAGE_GRAPHICS: "Grafika"
 SETTINGS_PAGE_INTERFACE: "Rozhraní"
 SETTINGS_PAGE_SYSTEM: "Systém"
 SETTINGS: "Nastavení"
