l_polish:
 message_settings_tab_settings: "Nastavení"
 message_settings_tab_log: "Protokol zpráv"
 MESSAGE_SETTINGS_WINDOW_NAME: "Nastavení zpráv"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Kliknutím otevřete Nastavení zpráv#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nUpravte četnost a viditelnost zpráv podle filtrovaných skupin."
 MESSAGE_SETTINGS_WINDOW_RESET: "Obnovit výchozí"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Obnovit nastavení zpráv#!\n#I Kliknutím obnovíte aktuální změny na výchozí nastavení#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Použít změny"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Kliknutím zavřete okno Nastavení zpráv a uložíte aktuální změny#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Kanál"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Krátké upozornění"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Vyskakovací okno"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Nikdy"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Skupina filtrů"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Název skupiny filtrů zpráv"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Zobrazení"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Jak zobrazovat zprávy z této skupiny filtrů"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pozastavení"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Zda se má hra pozastavit, když se objeví zprávy z této skupiny filtrů"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Přepnout automatické pozastavení#!\n#I Přepněte, zda se má hra pozastavit, když se objeví zprávy z této skupiny filtrů#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Zavřít zprávu#!\n#I Kliknutím zavřete aktuální zprávu a zobrazíte další ve frontě#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Vlastní zpráva"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Vlastní zpráva#!\n#I Kliknutím napište vlastní zprávu sobě a zvolte, kdy ji chcete obdržet#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Datum doručení: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Nadpis:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Popis:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Zahodit"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Zahodit zprávu#!\n#I Kliknutím zahodíte aktuální zprávu#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Odeslat"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Odeslat#!\n#I Kliknutím odešlete aktuální zprávu#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Den"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Měsíc"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Rok"
