l_polish:
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Vzhled"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Popis:"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nUpravte frekvenci a viditelnost zprávy podle filtrovaných skupin."
 MESSAGE_SETTINGS_WINDOW_NAME: "Nastavení zpráv"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Nikdy"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pauza"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Přepnout automatickou pauzu#!\n#I Přepněte, aby se hra pozastavila, když se objeví zprávy tohoto filtru#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Měsíc"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Klikněte pro otevření Nastavení zpráv#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Kanál"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Titulek:"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Vyskakovací okno"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Rok"
 MESSAGE_SETTINGS_WINDOW_RESET: "Obnovit na výchozí"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Skupina filtrů"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Odeslat"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Datum příjezdu: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Toast"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Použít změny"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Vlastní zpráva#!\n#I Klikněte pro napsání vlastní zprávy pro sebe a vyberte, kdy ji chcete obdržet#!"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Obnovit nastavení zpráv#!\n#I Klikněte pro obnovení aktuálních změn na výchozí nastavení#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Zrušit zprávu#!\n#I Klikněte pro zrušení aktuální zprávy#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Odeslat#!\n#I Klikněte pro odeslání aktuální zprávy#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Pokud by se hra měla pozastavit, když se objeví zprávy tohoto filtru"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Jak zobrazit zprávy této skupiny filtrů"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Den"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Zrušit"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Klikněte pro zavření okna Nastavení zpráv a uložení aktuálních změn#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Zamítnout zprávu#!\n#I Klikněte pro zamítnutí aktuální zprávy a zobrazení další zprávy v řadě#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Vlastní zpráva"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Název skupiny filtru zpráv"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)!"
