l_polish:
 SETTING_DEBUG_SAVES: "Počet ladicích uložení"
 SETTING_TUTORIAL: "Výukový režim"
 SETTING_DISABLED_HINTS: "Vypnuté rady"
 SETTING_TOOLTIP_DELAY: "Prodleva nápovědy"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nNastavuje prodlevu před zobrazením nápovědy."
 SETTING_TOOLTIP_UNLOCK_TIME: "Prodleva odemčení"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nNastavuje prodlevu před odemčením nápovědy."
 SETTING_TOOLTIP_LOCK_TIME: "Prodleva uzamčení"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nNastavuje prodlevu před uzamčením nápovědy."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Prodleva otevření při uzamčení"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nNastavuje prodlevu před uzamčením nápovědy, když je již otevřena jiná nápověda."
 SETTING_Sound_Effects: "Všechny zvukové efekty"
 SETTING_Sound_Effects_TOOLTIP: "#T Hlasitost zvukových efektů\n#!Nastavuje hlasitost VŠECH zvukových efektů."
 SETTING_Ambience: "Okolní zvuky"
 SETTING_Ambience_TOOLTIP: "#T Hlasitost okolních zvuků\n#!Nastavuje hlasitost zvuků okolního prostředí."
 SETTING_TOOLTIP_MODE: "Režim nápovědy"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nNastavuje způsob „uzamykání“ nápověd, který umožňuje zobrazovat nápovědy uvnitř dalších nápověd."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Pohyb myši"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nNápovědy se automaticky uzamknou na místě, dokud se kurzor nevzdálí."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Uzamčení akcí"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nNápovědy uzamkneš a odemkneš stisknutím #V prostředního tlačítka myši#!."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Časované uzamčení"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nNápovědy se uzamknou na místě, pokud se kurzor po krátkou dobu nepohne. #weak (Výchozí nastavení.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Ostatní"
 SETTINGS_CATEGORY_TOOLTIPS: "Nápovědy"
 SETTINGS_CATEGORY_SFX: "Konkrétní zvukové efekty"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Obecné"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Ovládání mapy"
 SETTINGS_CATEGORY_SAVE_GAMES: "Uložené hry"
 SETTINGS_CATEGORY_LANGUAGE: "Jazyk"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Pokročilé – Obecné"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Pokročilé – Mapa"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Pokročilé – Postavy"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portréty"
 SETTINGS_CATEGORY_GAME_EVENTS: "Události"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Atmosféra"
 SETTINGS_CATEGORY_MULTIPLAYER: "Hra více hráčů"
 SETTINGS_CATEGORY_MAP: "Mapa"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Zobrazovat drastické nemoci a zranění"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nNastavuje, zda se na portrétech postav budou zobrazovat drastická zranění a nemoci."
 SETTING_SHOW_NUDITY: "Zobrazovat nahotu"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nNastavuje, zda mohou být postavy zobrazeny nahé."
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Stahovatelný obsah"
 SETTING_SHOW_CONTENT_SOURCE: "Zobrazovat DLC události"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nNastavuje, zda se u událostí zobrazí, ze kterého DLC pocházejí."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Pomalý pohyb kamery v Královském dvoře"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nUrčuje, zda se má kamera v Královském dvoře během nečinnosti pomalu pohybovat po dvoře.\n\nPokud jsou vypnuté animované postavy, nemá toto nastavení žádný účinek."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Plynulé přechody v Královském dvoře"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nUrčuje, zda se má kamera v Královském dvoře plynule přesouvat na nové místo.\n\nPokud jsou vypnuté animované postavy, nemá toto nastavení žádný účinek."
 NEVER: "Nikdy"
 MONTHLY: "Každý měsíc"
 HALFYEAR: "Každých 6 měsíců"
 YEARLY: "Každý rok"
 FIVE_YEAR: "Každých 5 let"
 SETTINGS_CATEGORY_TUTORIAL: "Výukový režim"
 SETTING_REACTIVE_TUTORIAL: "Zobrazovat kontextové rady"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nNastavuje, zda má hra zobrazovat výukové rady reagující na způsob, jakým hraješ. Užitečné pro nové hráče Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Zobrazovat doporučení"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nNastavuje, zda ti má hra v pravidelných intervalech doporučovat, co můžeš udělat. Užitečné pro nové hráče Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Obnovit kontextové rady"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Obnovit kontextové rady#!\nJiž zobrazené kontextové rady se znovu objeví."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Obnovit kontextové rady"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Opravdu chceš obnovit kontextové rady?"
 SETTING_ADVANCED_SHADERS: "Pokročilé shaderové efekty"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Pokročilé shaderové efekty\n#!Tato možnost zapne pokročilé shaderové efekty.\n\nJejím vypnutím můžeš zvýšit výkon, některé efekty, například terén a voda, však mohou vypadat hůře."
 SETTING_WINTER_PARTICLE_EFFECTS: "Zimní částicové efekty"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nUrčuje, zda se mají zobrazovat částicové efekty, když v některých oblastech mapy panuje zima.\n\nJejich vypnutím můžeš zvýšit výkon."
 SETTING_RESET_CAMERA_ROTATION: "Obnovení natočení kamery"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nUrčuje, zda se má kamera poté, co ji natočíš, automaticky vrátit do výchozí polohy."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Naklánět kameru při oddalování"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nUrčuje, zda se má kamera při oddalování naklánět směrem k výchozímu sklonu."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Postavy v pozadí dvorské scény"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nUrčuje, zda se mají ve 3D scéně Královského dvora zobrazovat méně důležité postavy v pozadí."
 SETTING_MAP_HIGHLIGHT: "Zvýraznění kurzoru na mapě"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nUrčuje intenzitu zvýraznění kurzoru na mapě."
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Zvýraznění nejvyššího vládce na mapě"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nUrčuje, kdy se při výběru panství zvýrazní jeho nejvyšší vládce."
 OPTION_ALWAYS: "Vždy"
 OPTION_TRIBUTARY_ONLY: "Pouze tributáři"
 BASED_ON_ZOOM_LEVEL: "Dynamicky"
 ALWAYS_HIDE: "Vždy skrýt"
 ALWAYS_SHOW: "Vždy zobrazit"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Pobřežní hranice"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nTato možnost určuje, kdy se mají zobrazovat pobřežní hranice panství.\nPokud zvolíš $BASED_ON_ZOOM_LEVEL$, při detailním přiblížení budou skryté.\n\nVolba $ALWAYS_SHOW$ nebo $ALWAYS_HIDE$ může zvýšit výkon, pobřežní hranice panství se však nebudou skrývat dynamicky."
 SETTINGS_DISCARD_CHANGES: "Zahodit změny"
 ONLY_TOOLTIPS: "Pouze v nápovědách"
 OPTIONS_AND_TOOLTIPS: "U voleb a v nápovědách"
 NOWHERE: "Nikde"
 SETTING_SHOW_EVENT_SHORTCUTS: "Zobrazovat klávesové zkratky voleb událostí"
 SETTING_SHOW_EVENT_SHORTCUTS_TOOLTIP: "#T $SETTING_SHOW_EVENT_SHORTCUTS$#!\nNastavuje, kde se mají zobrazovat čísla klávesových zkratek voleb událostí.\nZkratky:\n#i Shift+číslo vybere volbu\nAlt+číslo zobrazí náhled jedné volby a potvrdí ji\nAlt+E zobrazí náhled všech voleb#!"
 SETTING_HUD_SKIN: "Vzhled rozhraní (HUD)"
 default: "Výchozí"
 iberian: "@fateofiberia_icon! $DLC005_FP2$"
 Norse: "@wrath_icon! $DLC003_FP1$"
 byzantine: "@roadstopower_icon! $DLC014_EP3$"
 iranian: "@legacyofpersia_icon! $DLC010_FP3$"
 nomad: "@khansofthesteppe_icon! $DLC020_CE2$"
 asia: "@allunderheaven_icon! $DLC022_EP4$"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nNastavuje vzhled rozhraní HUD, tedy 2D uživatelského rozhraní zobrazeného na hlavní herní obrazovce.\n\nPokud je vybráno $hud_skin_auto$, vzhled HUD se bude měnit podle kultury, víry a hlavního sídla panství hráče."
 SETTING_RICH_PRESENCE: "Podrobnosti o herní aktivitě"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nPokud to tvá platforma podporuje, zobrazí přátelům informace o tvé aktuální herní relaci."
 SETTING_USE_DYNASTY_NAMED_REALMS: "Panství pojmenovaná po dynastii"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nNěkteré kultury pojmenovávají svůj primární titul podle své dynastie, například Abbásovci."
 map_table_style_auto: "Dynamický"
 map_table_style_western: "Výchozí"
 map_table_style_ce1: "@legendsofthedead_icon! $DLC011_CE1$"
 map_table_style_ep3: "@roadstopower_icon! $DLC014_EP3$"
 map_table_style_tgp: "@allunderheaven_icon! $DLC022_EP4$"
 SETTING_MAP_TABLE_STYLE: "Vzhled mapového stolu"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nNastavuje vzhled mapového stolu, tedy mapy a 3D prostředí zobrazeného při oddálení.\n\nPokud je vybráno $map_table_style_auto$, vzhled mapového stolu se zvolí podle aktuálního hráče a jeho postavy."
 SETTING_SHOW_EVENT_NAME_PLATES: "Zobrazovat jmenovky v událostech"
 SETTING_SHOW_EVENT_NAME_PLATES_TOOLTIP: "#T $SETTING_SHOW_EVENT_NAME_PLATES$#!\nZobrazuje v událostech jména postav, vztahy a mínění.\nNápovědy postav se navíc budou zobrazovat nad jmenovkami namísto portrétů, což usnadní výběr.\nPlatí pouze pro běžné události, při duelech a aktivitách je tato možnost vypnutá."
 SETTINGS_CATEGORY_STYLING: "Vzhled rozhraní"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Grafické efekty nemocí"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nNastavuje, zda se mají na mapě zobrazovat efekty nemocí."
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Grafické efekty legend"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nNastavuje, zda se mají na mapě zobrazovat efekty legend."
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Podrobné ikony [Concept('raid','nájezdů')|E]"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nNastavuje, zda mají ikony [Concept('raid','nájezdů')|E] na mapě používat zjednodušenou, nebo podrobnou podobu.\n\n#I Pokud je tato možnost zapnutá, podržením Alt zobrazíš všechny državy s kořistí, které můžeš [Concept('raid','vyplenit')|E].#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Podrobné ikony [Concept('barter','směny')|E]"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nNastavuje, zda mají ikony [Concept('barter','směny')|E] na mapě používat zjednodušenou, nebo podrobnou podobu.\n\n#I Pokud je tato možnost zapnutá, podržením Alt zobrazíš všechny državy s kořistí, v nichž můžeš [Concept('barter','směňovat')|E].#!"
 SETTING_PAPER_MAP_STYLE: "Vzhled papírové mapy"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nNastavuje vzhled mapy zobrazené při oddálení.\n\nPokud je vybráno $paper_map_style_auto$, papírová mapa převezme vzhled nastavený u možnosti „$SETTING_MAP_TABLE_STYLE$“."
 paper_map_style_auto: "Dynamický"
 paper_map_style_western: "Výchozí"
 paper_map_style_tgp: "$DLC022_EP4$"
 SETTING_ADAPTIVE_FRAMERATE: "Adaptivní snímková frekvence"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Snižuje snímkovou frekvenci, pokud se zpomalí chod hry, aby zlepšilo herní výkon."
 SETTING_HIDE_MAP_TABLE: "Skrýt mapový stůl"
 SETTING_HIDE_MAP_TABLE_TOOLTIP: "#T $SETTING_HIDE_MAP_TABLE$\n#!Skryje geometrii mapového stolu."
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Stíny mraků"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nNastavuje, zda se mají na terénu zobrazovat stíny mraků."
 SETTING_HAS_TREE_DITHERING_ENABLED: "Vyhlazování stromů"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nNastavuje, zda se má na stromy použít dithering pro vyhlazení hran."
 SETTING_MAP_BRIGHTNESS: "Jas papírové mapy"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_BRIGHTNESS$#!\nUrčuje intenzitu jasu papírové mapy."
