l_polish:
 SETTING_REFRACTION: "Lom světla"
 SETTING_REFRACTION_QUALITY: "Kvalita lomu světla"
 SETTING_MAPOBJECT_QUALITY: "Objekty na mapě"
 SETTING_MAP_SSAO: "SSAO mapy"
 SETTING_DOF: "Hloubka ostrosti"
 SETTING_LENS_FLARE: "Odlesky objektivu"
 SETTING_SECONDARY_LENS_FLARE: "Sekundární odlesky objektivu"
