l_polish:
 SETTING_DOF: "Hlavní hloubka ostrosti"
 SETTING_LENS_FLARE: "Odlesk objektivu"
 SETTING_MAPOBJECT_QUALITY: "Kvalita mapových objektů"
 SETTING_MAP_SSAO: "Mapa SSAO"
 SETTING_REFRACTION_QUALITY: "Kvalita lomu"
 SETTING_REFRACTION: "Lom"
 SETTING_SECONDARY_LENS_FLARE: "Druhý odlesk objektivu"
