l_polish:
 SETTING_DOF:0 "Hlavní hloubka ostrosti"
 SETTING_LENS_FLARE: "Odlesk objektivu"
 SETTING_MAPOBJECT_QUALITY:0 "Kvalita mapových objektů"
 SETTING_MAP_SSAO:0 "Mapa SSAO"
 SETTING_REFRACTION_QUALITY:0 "Kvalita lomu"
 SETTING_REFRACTION:0 "Lom"
 SETTING_SECONDARY_LENS_FLARE: "Druhý odlesk objektivu"
